from colorama import init
from colorama import Fore, Back, Style
import os
import telebot
init()
print(Fore.RED + '  ██████  ██▓███   ▄▄▄       ███▄ ▄███▓ ██▓  ▄████ ')
print(Fore.RED + '▒██    ▒ ▓██░  ██▒▒████▄    ▓██▒▀█▀ ██▒▓██▒ ██▒ ▀█▒')
print(Fore.RED + '░ ▓██▄   ▓██░ ██▓▒▒██  ▀█▄  ▓██    ▓██░▒██▒▒██░▄▄▄░')
print(Fore.RED + '  ▒   ██▒▒██▄█▓▒ ▒░██▄▄▄▄██ ▒██    ▒██ ░██░░▓█  ██▓')
print(Fore.RED + '▒██████▒▒▒██▒ ░  ░ ▓█   ▓██▒▒██▒   ░██▒░██░░▒▓███▀▒')
print(Fore.RED + '▒ ▒▓▒ ▒ ░▒▓▒░ ░  ░ ▒▒   ▓▒█░░ ▒░   ░  ░░▓   ░▒   ▒ ')
print(Fore.RED + '░ ░▒  ░ ░░▒ ░       ▒   ▒▒ ░░  ░      ░ ▒ ░  ░   ░ ')
print(Fore.RED + '░  ░  ░  ░░         ░   ▒   ░      ░    ▒ ░░ ░   ░ ')
print(Fore.RED + '      ░                 ░  ░       ░    ░        ░ ')
print(Fore.GREEN + 'A free telegram spammer!')
print('')
print(Fore.YELLOW + 'For create a bot and get a token use: @BotFather')
print(Fore.MAGENTA + 'Enter your token:')
TOKEN = input()
os.system("cls")
bot = telebot.TeleBot(TOKEN)
print(Fore.RED + '  ██████  ██▓███   ▄▄▄       ███▄ ▄███▓ ██▓  ▄████ ')
print(Fore.RED + '▒██    ▒ ▓██░  ██▒▒████▄    ▓██▒▀█▀ ██▒▓██▒ ██▒ ▀█▒')
print(Fore.RED + '░ ▓██▄   ▓██░ ██▓▒▒██  ▀█▄  ▓██    ▓██░▒██▒▒██░▄▄▄░')
print(Fore.RED + '  ▒   ██▒▒██▄█▓▒ ▒░██▄▄▄▄██ ▒██    ▒██ ░██░░▓█  ██▓')
print(Fore.RED + '▒██████▒▒▒██▒ ░  ░ ▓█   ▓██▒▒██▒   ░██▒░██░░▒▓███▀▒')
print(Fore.RED + '▒ ▒▓▒ ▒ ░▒▓▒░ ░  ░ ▒▒   ▓▒█░░ ▒░   ░  ░░▓   ░▒   ▒ ')
print(Fore.RED + '░ ░▒  ░ ░░▒ ░       ▒   ▒▒ ░░  ░      ░ ▒ ░  ░   ░ ')
print(Fore.RED + '░  ░  ░  ░░         ░   ▒   ░      ░    ▒ ░░ ░   ░ ')
print(Fore.RED + '      ░                 ░  ░       ░    ░        ░ ')
print(Fore.GREEN + 'A free telegram spammer!')
print(Fore.GREEN + 'Coded by ReClean Bfresher')
print(Fore.YELLOW + 'Enter text:')
text = input()
print('How many times to repeat the text?')
repeat = int(input())
print(Fore.MAGENTA + 'Bot started!')
@bot.message_handler(func=lambda message: True)
def echo_message(message):
    bot.reply_to(message, text * repeat)
    print(Fore.GREEN + 'Message sended!')
bot.polling()